// Code generated by protoc-gen-go.
// source: chd.proto
// DO NOT EDIT!

package mph

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type CHDProto struct {
	R                []uint64 `protobuf:"varint,1,rep,name=r" json:"r,omitempty"`
	Indicies         []uint64 `protobuf:"varint,2,rep,name=indicies" json:"indicies,omitempty"`
	Keys             [][]byte `protobuf:"bytes,3,rep,name=keys" json:"keys,omitempty"`
	Values           [][]byte `protobuf:"bytes,4,rep,name=values" json:"values,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CHDProto) Reset()         { *m = CHDProto{} }
func (m *CHDProto) String() string { return proto.CompactTextString(m) }
func (*CHDProto) ProtoMessage()    {}

func (m *CHDProto) GetR() []uint64 {
	if m != nil {
		return m.R
	}
	return nil
}

func (m *CHDProto) GetIndicies() []uint64 {
	if m != nil {
		return m.Indicies
	}
	return nil
}

func (m *CHDProto) GetKeys() [][]byte {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *CHDProto) GetValues() [][]byte {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
}
