# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='chd.proto',
  package='mph',
  serialized_pb='\n\tchd.proto\x12\x03mph\"D\n\x08\x43HDProto\x12\t\n\x01r\x18\x01 \x03(\x04\x12\x0f\n\x07indices\x18\x02 \x03(\x04\x12\x0c\n\x04keys\x18\x03 \x03(\x0c\x12\x0e\n\x06values\x18\x04 \x03(\x0c')




_CHDPROTO = descriptor.Descriptor(
  name='CHDProto',
  full_name='mph.CHDProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='r', full_name='mph.CHDProto.r', index=0,
      number=1, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='indices', full_name='mph.CHDProto.indices', index=1,
      number=2, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='keys', full_name='mph.CHDProto.keys', index=2,
      number=3, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='values', full_name='mph.CHDProto.values', index=3,
      number=4, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=18,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['CHDProto'] = _CHDPROTO

class CHDProto(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CHDPROTO
  
  # @@protoc_insertion_point(class_scope:mph.CHDProto)

# @@protoc_insertion_point(module_scope)
